# Generated by Django 4.1.5 on 2023-04-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='amount',
        ),
    ]
